//	contains title, bootstrap, meta, flexslider, modernizr, and custom css
document.write(
    '<div class="image-bar-mainbar span8">'
	+'<div class="flexslider">'
		+'<ul class="slides">'
			+'<li>'
				+'<img src="./img/flexslider/burbank0.jpg" width="1100" height="585" alt="Burbank Place Apartments Parking Lot" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank1.jpg" width="1100" height="585" alt="Burbank Place Apartments in Winter" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank2.jpg" width="1100" height="585" alt="Burbank Place Apartments in Spring" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank3.jpg" width="1100" height="585" alt="Burbank Place Apartments Front in Winter" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank4.jpg" width="1100" height="585" alt="Burbank Place Apartments in Summer" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank5.jpg" width="1100" height="585" alt="Burbank Place Apartments at Night" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank6.jpg" width="1100" height="585" alt="137 Emerald St South Hamilton, ON" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank7.jpg" width="1100" height="585" alt="Burbank Place Apartments Backyard" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank8.jpg" width="1100" height="585" alt="Burbank Place Apartments Summer" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank9.jpg" width="1100" height="585" alt="Burbank Place Apartments LTD" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank10.jpg" width="1100" height="585" alt="Burbank Place Apartments Garden" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank11.jpg" width="1100" height="585" alt="Burbank Place Apartments" />'
			+'</li>'
			+'<li>'
				+'<img src="./img/flexslider/burbank12.jpg" width="1100" height="585" alt="Burbank Place Apartments Winter" />'
			+'</li>'
		+'</ul>'
	+'</div>'
);