//	contains title, bootstrap, meta, flexslider, modernizr, and custom css
document.write(
    '<meta content="charset=utf-8">'
	+'<meta name="viewport" content="width=device-width, initial-scale=1.0">'
    +'<meta name="author" content="Radomir Wojcik">'
    +'<meta name="copyright" content="Copyright 2014 Radomir Wojcik radtek.ca. All rights reserved.">'
    +'<meta name="description" content="Website for Burbank Place Apartments Limited Hamilton Cooperative Community Apartments near doowntown Hamilton.">'
    +'<meta name="keywords" content="Co-operative Community; Hamilton co-op apartments; affordable living; affordable apartments; Hamilton apartments; pet-friendly community"> '
	+'<link rel="stylesheet" href="css/bootstrap.css">'
	+'<link rel="stylesheet" href="css/bootstrap-responsive.css">'
	+'<link rel="stylesheet" href="css/lightbox.css">'
	+'<link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" />'
	+'<link rel="stylesheet" href="css/main.css">'
    +'<script src="js/libs/modernizr.js"></script>'
    +'<script src="js/libs/jquery.min.js"></script>'
    +'<script src="js/libs/lightbox.js"></script>'
    +'<script src="js/libs/bootstrap.js"></script>'
    +'<script type="text/javascript">var switchTo5x=true;</script>'
    +'<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>'
    +'<script type="text/javascript">stLight.options({publisher: "87d14b75-7d21-4e2d-91a4-6eb974f26cb3", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>'
    );
