document.write('<div class="news-bar-bullets">'
    +'<div class="news-bar-item-line1">MAINTENANCE</div> <div class="news-bar-item-line2">INCLUDES:</div>'
        +'<ul class="featured-list">'
            +'<li>Cable TV from Cogeco</li>'
            +'<li>Parking</li>'
            +'<li>Central Heating</li>'
            +'<li>Laundry</li>'
            +'<li>Water</li>'
            +'<li>Storage Locker</li>'
            +'<li>Property Taxes</li>'
            +'<li>Use of Workshop</li>'
            +'<li>Use of Bicycle Room</li>'
            +'<li>Building Insurance</li>'
            +'<li>Common Area Expenses</li>'
            +'<li>Capital Savings</li>'
            +'<li>Camera Surveillance</li>'
        +'</ul>'
    +'</div>'
    );

